### PR TITLE
Modmod

### PR DESCRIPTION
**Pull request by victorgeel**
tunnel core

### CODE REVIEW

**Review by SpherionOS — APPROVED** [review]
Thank you for changing the link to the official repo, I just used a local version of the tunnel core to prevent it breaking because at the time the latest psiphon release was bugged. I may have to remove the burmese as I can't read burmese, but thank you for your contribution

**Comment by victorgeel** [comment]
> Thank you for changing the link to the official repo, I just used a local version of the tunnel core to prevent it breaking because at the time the latest psiphon release was bugged. I may have to remove the burmese as I can't read burmese, but thank you for your contribution

**_Yes You can ..This is my test version only ...most useful version is Brainfuck...for android users..thanks_**

**Comment by SpherionOS** [comment]
Awesome, thank you. By the way, I have updated the installation script to install psiphon as an actual command instead of an executable in a local directory. This saves it to /usr/bin which won't work on android. However, all the old scripts are still there just in the /archive folder so you can still make psiphon in a local directory. Hope this helps with your work.

**Comment by victorgeel** [comment]
> Awesome, thank you. By the way, I have updated the installation script to install psiphon as an actual command instead of an executable in a local directory. This saves it to /usr/bin which won't work on android. However, all the old scripts are still there just in the /archive folder so you can still make psiphon in a local directory. Hope this helps with your work.

**I checked..both worked..**

**Comment by SpherionOS** [comment]
Oh excellent

**Comment by victorgeel** [comment]
> Oh excellent

hey bro...do u know how did Psiphon was setup akamai cdn in their server?
I don't see any sources in their server automation folder...did u found?

**Comment by SpherionOS** [comment]
I wouldnt know, I havent looked at their server automation sorry

**Pull request merged**
